### ISSUE TITLE
MV-HEVC Support Spatial Videos Apple Vision Pro

### ISSUE THREAD

**Issue by johan149** [TheWiselyBearded/sbs-generator#5] opened 2024-01-05 07:01 UTC
This would be a really cool functionality

**Comment by TheWiselyBearded** [comment] 2024-01-05 18:21
Hey @johan149, I totally agree 🔥

I tried looking into this early on then sunsetted my efforts. Eventually, I want to add support for both SBS and MV-HEVC. 

The problem is that MV-HEVC is not open source, one must either implement it themselves or find an implementation on github (or a mobile app). My goal for this repo is to make each process opens-source so that developers can tweak the knobs so-to-say. From my searches, I found [this repository](https://github.com/hasanmehmood/Multiview-Video-CODEC). 

Fortunately, from what I've read, Apple Vision Pro will support SBS videos as well, so the videos generated from this pipeline or others should support AVP. 

If this satisfies your request/question, please give a thumbs up so that I can close the issue :)

**Comment by johan149** [comment] 2024-01-22 20:30
I know there is nothing out there yet, BTW check this new depth algo that came out today. pretty cool.

https://github.com/LiheYoung/Depth-Anything

**Comment by TheWiselyBearded** [comment] 2024-01-29 20:02
planning to add support for it as we speak!

**Closed as completed by TheWiselyBearded** 2024-01-29 20:02 UTC
